spring:
  application:
    name: rentz
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres?autoReconnect=true&useSSL=false&createDatabaseIfNotExist=true
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
    hikari:
        auto-commit: false
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.PostgreSQLDialect
